"""init commit

Revision ID: eb06829aab95
Revises: 
Create Date: 2021-02-17 19:03:49.584484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb06829aab95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('path', sa.VARCHAR(length=128), nullable=True, comment='API路径'),
    sa.Column('description', sa.VARCHAR(length=64), nullable=True, comment='API描述'),
    sa.Column('api_group', sa.VARCHAR(length=32), nullable=True, comment='API分组'),
    sa.Column('method', sa.VARCHAR(length=16), nullable=True, comment='请求方法'),
    sa.PrimaryKeyConstraint('id'),
    comment='API管理表'
    )
    op.create_index(op.f('ix_sys_api_id'), 'sys_api', ['id'], unique=False)
    op.create_table('sys_authorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('authority_id', sa.Integer(), nullable=True, comment='权限id'),
    sa.Column('authority_name', sa.VARCHAR(length=32), nullable=True, comment='角色名'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父角色id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority_id'),
    sa.UniqueConstraint('parent_id'),
    comment='用户角色表'
    )
    op.create_index(op.f('ix_sys_authorities_id'), 'sys_authorities', ['id'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.VARCHAR(length=16), nullable=True, comment='手机号'),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True, comment='管理员昵称'),
    sa.Column('avatar', sa.VARCHAR(length=256), nullable=True, comment='管理员头像'),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False, comment='密码'),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=True, comment='邮箱是否激活 0=未激活 1=激活'),
    sa.Column('authority_id', sa.Integer(), nullable=True, comment='角色id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='系统用户表'
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_phone'), 'sys_user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_phone'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_authorities_id'), table_name='sys_authorities')
    op.drop_table('sys_authorities')
    op.drop_index(op.f('ix_sys_api_id'), table_name='sys_api')
    op.drop_table('sys_api')
    # ### end Alembic commands ###
